In [82]:
import pandas as pd
csv_path = "data/Data.csv"
df = pd.read_csv(csv_path, encoding="ISO-8859-1")
df.head()

Season(1-Winter, 2-Spring, 3-Summer, 4-Fall)  \
0                                         -0.33   
1                                         -0.33   
2                                         -0.33   
3                                         -0.33   
4                                         -0.33   

   Age at the time of analysis. 18-36 (0, 1)  \
0                                       0.69   
1                                       0.94   
2                                       0.50   
3                                       0.75   
4                                       0.67   

   Childish diseases (ie , chicken pox, measles, mumps, polio) 1) yes, 2) no.  \
0                                                  0                            
1                                                  1                            
2                                                  1                            
3                                                  0                            
4                                                  1                            

   Accident or serious trauma 1) yes, 2) no.  \
0                                          1   
1                                          0   
2                                          0   
3                                          1   
4                                          1   

   Surgical intervention 1) yes, 2) no.  \
0                                     1   
1                                     1   
2                                     0   
3                                     1   
4                                     0   

   High fevers in the last year 1) less than three months ago, 2) more than three months ago, 3) no  \
0                                                  0                                                  
1                                                  0                                                  
2                                                  0                                                  
3                                                  0                                                  
4                                                  0                                                  

   Frequency of alcohol consumption 1) several times a day, 2) every day, 3) several times a week, 4) once a week, 5) hardly ever or never  \
0                                                0.8                                                                                         
1                                                0.8                                                                                         
2                                                1.0                                                                                         
3                                                1.0                                                                                         
4                                                0.8                                                                                         

   Smoking habit 1) never, 2) occasional 3) daily.  \
0                                                0   
1                                                1   
2                                               -1   
3                                               -1   
4                                               -1   

   Number of hours spent sitting per day ene-16  \
0                                          0.88   
1                                          0.31   
2                                          0.50   
3                                          0.38   
4                                          0.50   

   Output Diagnosis(0-Normal, 1-Altered)  
0                                      0  
1                                      1  
2                                      0  
3                                      0  
4                                      1

In [83]:
df.columns = ['season', 'age', 'diseases', 'accident', 'surgery', 'fever', 'alcohol', 'smoking', 'sitting', 'diagnosis']

In [84]:
df_one = pd.get_dummies(df, columns=['fever'], prefix = ['fever'])
df_two = pd.get_dummies(df_one, columns=['alcohol'], prefix = ['alcohol'])
df_three = pd.get_dummies(df_two, columns=['smoking'], prefix = ['smoking'])

In [85]:
df_three.loc[df_three['sitting'] > 0.5, 'sitting'] = 1

In [86]:
df_three.loc[df_three['sitting'] <= 0.5, 'sitting'] = 0.5

In [87]:
df_four = pd.get_dummies(df_three, columns=['sitting'], prefix = ['sitting'])

In [88]:
df_five = pd.get_dummies(df_four, columns=['season'], prefix = ['season'])

In [89]:
df_five.loc[df_five['age'] > 0.5, 'age'] = 1

In [90]:
df_five.loc[df_five['age'] <= 0.5, 'age'] = 0.5

In [91]:
df_six = pd.get_dummies(df_five, columns=['age'], prefix = ['age'])
df_six.head()

diseases  accident  surgery  diagnosis  fever_-1  fever_0  fever_1  \
0         0         1        1          0         0        1        0   
1         1         0        1          1         0        1        0   
2         1         0        0          0         0        1        0   
3         0         1        1          0         0        1        0   
4         1         1        0          1         0        1        0   

   alcohol_0.2  alcohol_0.4  alcohol_0.6  ...  smoking_0  smoking_1  \
0            0            0            0  ...          1          0   
1            0            0            0  ...          0          1   
2            0            0            0  ...          0          0   
3            0            0            0  ...          0          0   
4            0            0            0  ...          0          0   

   sitting_0.5  sitting_1.0  season_-1.0  season_-0.33  season_0.33  \
0            0            1            0             1            0   
1            1            0            0             1            0   
2            1            0            0             1            0   
3            1            0            0             1            0   
4            1            0            0             1            0   

   season_1.0  age_0.5  age_1.0  
0           0        0        1  
1           0        0        1  
2           0        1        0  
3           0        0        1  
4           0        0        1  

[5 rows x 23 columns]

In [92]:
import numpy as np
import tensorflow as ts

from sklearn.preprocessing import LabelEncoder

from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Dense

In [93]:
print(df_six.dtypes)
print(df_six.values)

diseases        int64
accident        int64
surgery         int64
diagnosis       int64
fever_-1        uint8
fever_0         uint8
fever_1         uint8
alcohol_0.2     uint8
alcohol_0.4     uint8
alcohol_0.6     uint8
alcohol_0.8     uint8
alcohol_1.0     uint8
smoking_-1      uint8
smoking_0       uint8
smoking_1       uint8
sitting_0.5     uint8
sitting_1.0     uint8
season_-1.0     uint8
season_-0.33    uint8
season_0.33     uint8
season_1.0      uint8
age_0.5         uint8
age_1.0         uint8
dtype: object
[[0 1 1 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [1 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 0 0 1]
 [1 0 1 ... 0 0 1]
 [0 1 1 ... 0 0 1]]


In [94]:
X = df_six.drop("diagnosis", axis=1)
y = df_six["diagnosis"]

In [95]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [96]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y = label_encoder.transform(y_train)

In [97]:
for label, original_class in zip(encoded_y, y):
    print(original_class)
    print(label)

0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
1
0
1
0
0
0
0
1
0
0
0
0
0
1
0
1
1
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
1
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0


In [98]:
from keras.utils import to_categorical
one_hot_y = to_categorical(encoded_y)
one_hot_y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [99]:
model = Sequential()
model.add(Dense(units=6, activation='relu', input_dim=22))
model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=2, activation='softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_26 (Dense)             (None, 6)                 138       
_________________________________________________________________
dense_27 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_28 (Dense)             (None, 2)                 14        
Total params: 194
Trainable params: 194
Non-trainable params: 0
_________________________________________________________________


In [100]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [101]:
model.fit(X_train, one_hot_y, epochs=300, shuffle=True, verbose=2)

Epoch 1/300
 - 2s - loss: 0.5819 - acc: 0.7867
Epoch 2/300
 - 0s - loss: 0.5710 - acc: 0.8000
Epoch 3/300
 - 0s - loss: 0.5588 - acc: 0.8133
Epoch 4/300
 - 0s - loss: 0.5475 - acc: 0.8267
Epoch 5/300
 - 0s - loss: 0.5343 - acc: 0.8667
Epoch 6/300
 - 0s - loss: 0.5235 - acc: 0.8800
Epoch 7/300
 - 0s - loss: 0.5103 - acc: 0.8800
Epoch 8/300
 - 0s - loss: 0.4988 - acc: 0.8800
Epoch 9/300
 - 0s - loss: 0.4883 - acc: 0.8800
Epoch 10/300
 - 0s - loss: 0.4775 - acc: 0.8800
Epoch 11/300
 - 0s - loss: 0.4665 - acc: 0.8800
Epoch 12/300
 - 0s - loss: 0.4568 - acc: 0.8800
Epoch 13/300
 - 0s - loss: 0.4473 - acc: 0.8800
Epoch 14/300
 - 0s - loss: 0.4379 - acc: 0.8800
Epoch 15/300
 - 0s - loss: 0.4309 - acc: 0.8800
Epoch 16/300
 - 0s - loss: 0.4218 - acc: 0.8800
Epoch 17/300
 - 0s - loss: 0.4150 - acc: 0.8800
Epoch 18/300
 - 0s - loss: 0.4085 - acc: 0.8800
Epoch 19/300
 - 0s - loss: 0.4025 - acc: 0.8800
Epoch 20/300
 - 0s - loss: 0.3965 - acc: 0.8800
Epoch 21/300
 - 0s - loss: 0.3912 - acc: 0.8800
E

Epoch 171/300
 - 0s - loss: 0.2088 - acc: 0.8800
Epoch 172/300
 - 0s - loss: 0.2082 - acc: 0.8800
Epoch 173/300
 - 0s - loss: 0.2075 - acc: 0.8800
Epoch 174/300
 - 0s - loss: 0.2069 - acc: 0.8800
Epoch 175/300
 - 0s - loss: 0.2061 - acc: 0.8800
Epoch 176/300
 - 0s - loss: 0.2053 - acc: 0.8800
Epoch 177/300
 - 0s - loss: 0.2045 - acc: 0.8800
Epoch 178/300
 - 0s - loss: 0.2038 - acc: 0.8800
Epoch 179/300
 - 0s - loss: 0.2031 - acc: 0.8800
Epoch 180/300
 - 0s - loss: 0.2024 - acc: 0.8800
Epoch 181/300
 - 0s - loss: 0.2014 - acc: 0.8800
Epoch 182/300
 - 0s - loss: 0.2005 - acc: 0.8800
Epoch 183/300
 - 0s - loss: 0.2002 - acc: 0.8800
Epoch 184/300
 - 0s - loss: 0.1995 - acc: 0.8800
Epoch 185/300
 - 0s - loss: 0.1985 - acc: 0.8800
Epoch 186/300
 - 0s - loss: 0.1978 - acc: 0.8800
Epoch 187/300
 - 0s - loss: 0.1971 - acc: 0.8800
Epoch 188/300
 - 0s - loss: 0.1964 - acc: 0.8800
Epoch 189/300
 - 0s - loss: 0.1963 - acc: 0.8800
Epoch 190/300
 - 0s - loss: 0.1951 - acc: 0.8800
Epoch 191/300
 - 0s 

In [102]:
label_encoder2 = LabelEncoder()
label_encoder2.fit(y_test)
encoded_y_test = label_encoder.transform(y_test)

for label, original_class in zip(encoded_y_test, y):
    print(original_class)
    print(label)

0
0
1
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0


In [103]:
one_hot_y_test = to_categorical(encoded_y_test)
one_hot_y_test

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [104]:
model.fit(X_test, one_hot_y_test, epochs=300, shuffle=True, verbose=2)

Epoch 1/300
 - 0s - loss: 0.7867 - acc: 0.8800
Epoch 2/300
 - 0s - loss: 0.7843 - acc: 0.8800
Epoch 3/300
 - 0s - loss: 0.7793 - acc: 0.8800
Epoch 4/300
 - 0s - loss: 0.7722 - acc: 0.8800
Epoch 5/300
 - 0s - loss: 0.7633 - acc: 0.8800
Epoch 6/300
 - 0s - loss: 0.7530 - acc: 0.8800
Epoch 7/300
 - 0s - loss: 0.7416 - acc: 0.8400
Epoch 8/300
 - 0s - loss: 0.7293 - acc: 0.8400
Epoch 9/300
 - 0s - loss: 0.7164 - acc: 0.8400
Epoch 10/300
 - 0s - loss: 0.7028 - acc: 0.8400
Epoch 11/300
 - 0s - loss: 0.6891 - acc: 0.8000
Epoch 12/300
 - 0s - loss: 0.6753 - acc: 0.8000
Epoch 13/300
 - 0s - loss: 0.6614 - acc: 0.8000
Epoch 14/300
 - 0s - loss: 0.6474 - acc: 0.8000
Epoch 15/300
 - 0s - loss: 0.6335 - acc: 0.8000
Epoch 16/300
 - 0s - loss: 0.6211 - acc: 0.8000
Epoch 17/300
 - 0s - loss: 0.6089 - acc: 0.8000
Epoch 18/300
 - 0s - loss: 0.5966 - acc: 0.8000
Epoch 19/300
 - 0s - loss: 0.5845 - acc: 0.8000
Epoch 20/300
 - 0s - loss: 0.5728 - acc: 0.8000
Epoch 21/300
 - 0s - loss: 0.5613 - acc: 0.8000
E

Epoch 171/300
 - 0s - loss: 0.1495 - acc: 0.9200
Epoch 172/300
 - 0s - loss: 0.1486 - acc: 0.9200
Epoch 173/300
 - 0s - loss: 0.1478 - acc: 0.9200
Epoch 174/300
 - 0s - loss: 0.1469 - acc: 0.9200
Epoch 175/300
 - 0s - loss: 0.1461 - acc: 0.9200
Epoch 176/300
 - 0s - loss: 0.1452 - acc: 0.9200
Epoch 177/300
 - 0s - loss: 0.1444 - acc: 0.9200
Epoch 178/300
 - 0s - loss: 0.1436 - acc: 0.9200
Epoch 179/300
 - 0s - loss: 0.1427 - acc: 0.9200
Epoch 180/300
 - 0s - loss: 0.1419 - acc: 0.9200
Epoch 181/300
 - 0s - loss: 0.1412 - acc: 0.9200
Epoch 182/300
 - 0s - loss: 0.1405 - acc: 0.9200
Epoch 183/300
 - 0s - loss: 0.1397 - acc: 0.9200
Epoch 184/300
 - 0s - loss: 0.1390 - acc: 0.9200
Epoch 185/300
 - 0s - loss: 0.1383 - acc: 0.9200
Epoch 186/300
 - 0s - loss: 0.1377 - acc: 0.9200
Epoch 187/300
 - 0s - loss: 0.1370 - acc: 0.9200
Epoch 188/300
 - 0s - loss: 0.1363 - acc: 0.9200
Epoch 189/300
 - 0s - loss: 0.1357 - acc: 0.9200
Epoch 190/300
 - 0s - loss: 0.1351 - acc: 0.9200
Epoch 191/300
 - 0s 

In [105]:
import numpy as np

new_data = np.array([[1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0]])
print(model.predict_classes(new_data))

[0]


In [106]:
model.save("fertility_deep_neural.h5")